name: Package and Registry

on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string
  release:
    types: [created]

jobs:
  push-to-registy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/jefersonsmota/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PACKAGE_REGISTRY_SECRET}}
      - run: dotnet build --configuration Release ./${{ inputs.project-dir }}
      - name: Create the package
        run: dotnet pack --configuration Release ./${{ inputs.project-dir }}
      - name: Publish the package to GHPR
        run: dotnet nuget push ./${{ inputs.project-dir }}/bin/Release/*.nupkg