apiVersion: v1
kind: Pod
metadata:
  name: pod-front
  namespace: 3pmybil
  labels:
    app: pod-front
spec:
  containers:
  - name: front
    image: jsmota/dev:ngfront-3pmybil-1.0.0
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: 3pmybil-front-configmap
