name: Package and Registry

on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string

jobs:
  push-to-registy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dotnet restore --configuration Release ${{ inputs.project-dir }}
      - run: dotnet build --configuration Release ${{ inputs.project-dir }}
      - name: Create the package
        run: dotnet pack --configuration Release ${{ inputs.project-dir }}
      - name: Publish the package to GHPR
        run: dotnet nuget push ${{ inputs.project-dir }}/bin/Release/*.nupkg --api-key ${{secrets.PACKAGE_REGISTRY_SECRET}} --source "github"