name: Package and Registry

on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string

jobs:
  push-to-registy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup build .Net Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore ${{ inputs.project-dir }}
      - run: dotnet build --configuration Release ${{ inputs.project-dir }}
      - name: Create the package
        run: dotnet pack --configuration Release ${{ inputs.project-dir }}
      - name: Publish the package to GHPR
        run: dotnet nuget push ${{ inputs.project-dir }}/bin/Release/*.nupkg --api-key ${{secrets.PACKAGE_REGISTRY_SECRET}} --source "github"