name: pipeline-3pmybil
run-name: ${{ github.actor }}
on:
  push:
    branches:  [main]
  pull_request:
    branches: [main]

jobs:
  build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            dotnet-version: [ '7.0.x' ]
        
        steps:
          - uses: actions/checkout@4
          
          - name: Setup build .Net Core ${{ matrix.dotnet-version }}
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: ${{ matrix.dotnet-version }}
          
          - name: Install dependencies
            working-directory: ./WebApi
            run: dotnet restore
          
          - name: Build
            working-directory: ./WebApi
            run: dotnet build --configuration Release --no-restore
          
          - name: Test
            working-directory: ./WebApi
            run: dotnet test --no-restore --verbosity normal


